In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
vocab_size = 50
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[45, 45], [11, 31], [11, 27], [43, 24, 46], [31, 9, 13], [45, 45], [4, 9, 11], [1, 18], [1, 47], [19, 5]]


In [4]:
padding = pad_sequences(encoded_reviews, maxlen=4, padding='post')
print(padding)

[[45 45  0  0]
 [11 31  0  0]
 [11 27  0  0]
 [43 24 46  0]
 [31  9 13  0]
 [45 45  0  0]
 [ 4  9 11  0]
 [ 1 18  0  0]
 [ 1 47  0  0]
 [19  5  0  0]]


In [12]:
embbed_vector_size = 4
model = Sequential()
model.add(Embedding(vocab_size, embbed_vector_size, input_length=4, name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation="sigmoid"))


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:
x = padding
y = sentiment

In [15]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["acc"])

In [20]:
model.fit(x, y, epochs=48, verbose=0)

In [21]:
accuracy, loss = model.evaluate(x, y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.9000 - loss: 0.5688


In [22]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 4, 4)           │           200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 653 (2.55 KB)

 Trainable params: 217 (868.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 436 (1.71 KB)

In [25]:
weights = model.get_layer("embedding").get_weights()[0]

In [26]:
weights[6]

array([-0.03986009,  0.02917273, -0.03694707, -0.01323402], dtype=float32)